eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
spring:
  application:
    name: api-gateway
logging:
  level:
    root: INFO
  org:
    springframework:
      cloud:
        gateway: TRACE
        gateway.route.RouteDefinitionLocator: INFO
